name: My Docker Action

on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    container:
      seanmaxwell/godot-ci:4.0
    env:
      ITCHIO_USERNAME: ${{ env.ITCHIO_USERNAME }}
      ITCHIO_GAME: ${{ env.ITCHIO_GAME }}
      BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
      EXPORT_NAME: ${{ env.EXPORT_NAME }}
      PROJECT_PATH: ${{ env.PROJECT_PATH }}