# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: My Docker Action

on: push

env:
  GODOT_VERSION: 4.0
  ITCHIO_USERNAME: ${{github.repository.ITCHIO_USERNAME}}
  ITCHIO_GAME: ${{github.repository.ITCHIO_GAME}}
  BUTLER_API_KEY: ${{secrets.BUTLER_API_KEY}}
  EXPORT_NAME: ${{github.repository.EXPORT_NAME}}
  PROJECT_PATH: ${{github.repository.PROJECT_PATH}}

jobs:
  export-web:
    name: Web Export
    runs-on: ubuntu-20.04
    container:
      image: seanmaxwell/godot-ci:4.0
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
      - name: Web Build
        run: |
          mkdir -v -p build/web
          cd $PROJECT_PATH
          godot -v --export "HTML5" ../build/web/index.html
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: web
          path: build/web
